name: PR Labels

on: [pull_request_target]

jobs:
  size-labels:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: learningequality/pr-labeler@f3a503a1210b753b2f5406e6729e42f13cca4f4b
        with:
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          exclude_files: '^$'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
