name: PR Labels

on: [pull_request_target]

jobs:
  size-labels:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: learningequality/pr-labeler@817db6d2a884c8b5e0620032dd1b2fb15bbc1c72
        with:
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          exclude_files: '^$'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
